### ISSUE TITLE
Firefox Extenstion

### ISSUE THREAD

**Issue by thisishima** [AdobeDocs/platform-learn.en#1]
Issue in ./help/data-ingestion/web-sdk/introduction-to-the-experience-platform-debugger.md

Hello, 

Looks like the Experience Platform Debugger is not available in Firefox and hence the link in the above web page is giving an error. 
![debugger unavailable](https://user-images.githubusercontent.com/17186442/81873608-f1727380-9530-11ea-8d0c-c9c48f62c6c2.png)

**Comment by dwright-adobe** [comment]
Thanks for reporting this @thisishima . I will look into it.

**Comment by dwright-adobe** [comment]
@thisishima , again thanks for reporting this. the extension is back up and live. FF wanted some updates and took it down temporarily
