### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by anirudhan-c** [AdobeDocs/platform-learn.en#10]
The link to the following in Further Information' is broken :
Implement the Experience Cloud in Websites with Tags with Adobe Experience Platform Data Collection (https://experienceleague.adobe.com/docs/core-services-learn/implement-in-websites-with-launch/index.html?lang=en)

Please fix the link.

Issue in ./help/tutorial-comprehensive-technical-v22/modules/module1/ex1.md

**Comment by dwright-adobe** [comment]
Thanks for reporting this @anirudhan-c . @woutervangeluwe , i have fixed the link and pointed it to our new Web SDK tutorial.
