### ISSUE TITLE
 Developer Console Access Token Generation collection link for Github is not working

### ISSUE THREAD

**Issue by stripathi345** [AdobeDocs/platform-learn.en#16]
Hi Team,

Issue in ./help/tutorial-data-architect-and-engineer/set-up-developer-console-and-postman.md

The github link for the  Developer Console Access Token Generation collection json file is broken and give '404 not found error'.
Kindly resolve.

Thanks,
Saurbh

**Comment by dwright-adobe** [comment]
Thanks. Fixed!
