### ISSUE TITLE
Issue Facing as No such module in the Appdelegate file

### ISSUE THREAD

**Issue by RPRITHIBA** [AdobeDocs/platform-learn.en#2]
Follow the same step by step procedure. In between I'm facing the issue in the Appdelegate file while insert the import line into the file. eg. import AEPCore.  Issue in ./help/tutorial-mobile-ios-swift-implementation/install-the-mobile-sdk.md

**Comment by dwright-adobe** [comment]
What is the issue you are experiencing?
