### ISSUE TITLE
The "Create Identity Profile Field Group" and "Create Loyalty Field Group" calls inside the "Luma-Loyalty-Data"  Postman collection requires update

### ISSUE THREAD

**Issue by kartha01** [AdobeDocs/platform-learn.en#3]
Issue in ./help/platform/data-generator/import-sample-data.md

Link: https://experienceleague.adobe.com/docs/platform-learn/tutorials/import-sample-data.html?lang=en#

The  `Create Identity Profile Field Group` and `Create Loyalty Field Group` calls inside the `Luma-Loyalty-Data` collection by default uses the **_techmarketingdemos** namespace. This needs to be changed to the appropriate `tenant_id` value to reflect the user's namespace.
![image](https://user-images.githubusercontent.com/1424502/150071827-bc92ad4b-6076-4fa4-9635-f5b4dfa4be73.png)

Without this change the POST calls fail with 401. 

A note indicating this change would be a good addition to this tutorial.

**Comment by dwright-adobe** [comment]
This will now dynamically populate the `{{TENANT_ID}}` from the environment.
