### ISSUE TITLE
Layout not displaying correctly in the table. Also, sandbox id is...a placeholder?

### ISSUE THREAD

**Issue by ankurmehrotra** [AdobeDocs/platform-learn.en#30]
Issue in ./help/tutorial-comprehensive-technical/modules/module14/ex1.md

![image](https://user-images.githubusercontent.com/15048072/117428702-9a766300-af26-11eb-8ed0-b5dc7bc8d194.png)
![image](https://user-images.githubusercontent.com/15048072/117428781-a9f5ac00-af26-11eb-8f95-4b5c5e1105d2.png)

**Comment by dwright-adobe** [comment]
@woutervangeluwe

**Comment by woutervangeluwe** [comment]
@dwright-adobe this isn't an issue - the user isn't using the Chrome extension as indicated in the tutorial. should be closed.
