### ISSUE TITLE
Adjust to non-AEP Customers

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/platform-learn.en#30]
Issue in ./help/tutorial-web-sdk/overview.md

One piece of overall feedback is that now with all Experience Cloud organizations having the ability to deploy the AEP Web SDK via the new permissions in Data Collection, this same tutorial could be done with Non-AEP customers (which is how I went through this tutorial). A snippet or note about that in this overview section would be a good idea. I'll place several other comments in different sections calling out where small sections could be updated to account for this use case.

In the pre-requisite section, it talks about Adobe IDs, which aren't really a thing anymore. Perhaps just an adjustment to the sentence to ensure that the user has the right permissions without mentioning Adobe IDs would be the easiest fix.

**Comment by dwright-adobe** [comment]
updated--thanks for the feedback!
