### ISSUE TITLE
Non-AEP  customer Adjustment to Permissions

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/platform-learn.en#31]
Issue in ./help/tutorial-web-sdk/configure-permissions.md

For someone who isn't an AEP customer, several of the bulleted items under Experience Platform should be listed in the Data Collection section as that is where they're going to view schemas, namespaces, and data streams. Links to documentation with overviews of those things might also be a good thing. Lastly, the concept of a sandbox (production or otherwise) isn't a concept a non-AEP customer is going to know about. Perhaps explaining or providing links to what sandboxes are, but also explaining that they won't be able to change the sandbox as a non-AEP customer might help. It may also be a good place to explain that whatever changes they make will show up in their production sandbox should they become AEP customers in the future.

**Comment by dwright-adobe** [comment]
I hear your point, but in the admin console these permissions are assigned in the "Experience Platform" product. Non-Platform customers should see this product listed with limited permission items. I clarify this in the Experience Platform section "These features should be available to all Experience Cloud customers, even if you are not a customer of a Platform-based application like Real-time CDP."

The "Prod" sandbox is also visible there.

Links to the docs are in.
