### ISSUE TITLE
14.2.4 Create your Offer Activity

### ISSUE THREAD

**Issue by ankurmehrotra** [AdobeDocs/platform-learn.en#32]
Issue in ./help/tutorial-comprehensive-technical/modules/module14/ex2.md

Unfortunately this has moved to Offers>decisions screen. For a new trainee it will be very hard to figure where **Activites** are now. Pasting new one for reference.
![image](https://user-images.githubusercontent.com/15048072/117432926-31451e80-af2b-11eb-85b2-828f5aa894fd.png)

**Comment by dwright-adobe** [comment]
@woutervangeluwe

**Comment by woutervangeluwe** [comment]
@dwright-adobe this is also already fixed
