### ISSUE TITLE
Sandbox selection

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/platform-learn.en#34]
Issue in ./help/tutorial-web-sdk/configure-datastream.md

Step 2 of selecting a sandbox does not apply for customers without an AEP license. 

Additionally, just like you have a note saying that you recommend a development sandbox, we may want to add language around how that might work for non-AEP customers since everything is done in their production environment.

**Comment by dwright-adobe** [comment]
I just updated the note to:
"If you are the customer of a Platform-based application like Real-time CDP, we recommend using a development sandbox for this tutorial. If you are not, use the Prod sandbox."
It should go live in the next few hours.
