### ISSUE TITLE
The namespace in all the sample JSON data needs to be updated before using it in the tutorial

### ISSUE THREAD

**Issue by kartha01** [AdobeDocs/platform-learn.en#4]
Following the tutorial at:
https://experienceleague.adobe.com/docs/platform-learn/tutorials/import-sample-data.html?lang=en#

downloading and importing the dataset directly does work. It fails with:
![image](https://user-images.githubusercontent.com/1424502/150408811-61c4bc7d-ac5e-47a9-a80e-d360dc11e261.png)

The reason being that the dataset expect the `_techmarketingdemos` namespace/tenant_id, which may not exist for the user. It would useful to add a note to either create that corresponding `tenant_id` or update the sample data JSON to reflect the user's `tenant_id`.

**Comment by dwright-adobe** [comment]
@kartha01 ,
Thanks for catching that! I have update the tutorial with a new step for this: "20. In the luma-data folder, open all of the json files in a text editor and replace all instances of _techmarketingdemos with your own tenant id, preceded by an underscore."
