### ISSUE TITLE
Wrong Placement type in instructions

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/platform-learn.en#4]
Issue in ./help/tutorial-comprehensive-technical/modules/module14/ex2.md

@woutervangeluwe ,
You have the text 
"For Representation 3, select:

Channel: Non-digital
Placement: Non-digital - Image"

but i think you want the user to select "Placement: Non-digital - Text" based on the later instructions.

**Comment by dwright-adobe** [comment]
@woutervangeluwe , can this issue be closed?

**Comment by woutervangeluwe** [comment]
@dwright-adobe yes this is fixed
