### ISSUE TITLE
VEC helper extension is required instead of possibly

### ISSUE THREAD

**Issue by morritza** [AdobeDocs/platform-learn.en#45]
Issue in ./help/tutorial-migrate-target-websdk/render-vec-activities.md

"Install the Visual Editing Helper browser extension, if required"
You are required to install the extension in order to make the page to load in the VEC. Otherwise Target wont find the library on the page from what i've learnt.

Official Platform Doc regarding VEC:
"To use the VEC with a Platform Web SDK implementation, install and activate either the [Firefox](https://addons.mozilla.org/en-US/firefox/addon/adobe-target-vec-helper/) or [Chrome](https://chrome.google.com/webstore/detail/adobe-target-vec-helper/ggjpideecfnbipkacplkhhaflkdjagak) VEC Helper Extension."
https://experienceleague.adobe.com/docs/experience-platform/edge/personalization/adobe-target/target-overview.html?lang=en#using-the-adobe-target-vec

**Comment by dwright-adobe** [comment]
fixed this, thanks
