### ISSUE TITLE
Custom events migrated to monitor hooks - please verify with BU

### ISSUE THREAD

**Issue by morritza** [AdobeDocs/platform-learn.en#46]
Issue in ./help/tutorial-migrate-target-websdk/detailed-comparison.md

"Custom Events: Partially supported via [monitoring hooks](https://github.com/adobe/alloy/wiki/Monitoring-Hooks)"

On the table its stated alloy's hooks can be used for a Target custom event replacement. But thats not really recommended as the official doc is mentioning:

"..This is useful for developing debugging tools and to capture Alloy logs."
https://github.com/adobe/alloy/wiki/Monitoring-Hooks

**Comment by dwright-adobe** [comment]
Thanks @morritza , closing this issue as i think I removed this reference a while ago.
