### ISSUE TITLE
Help doc doesn't refer to kndctr cookies

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/platform-learn.en#47]
Issue in ./help/data-collection/edge/generate-first-party-device-ids.md

The diagram and info on this help doc doesn't refer to the "kndctr" cookie which is always used to store the ECID generated by the Edge. It only refers to the AMCV_ cookie. However, this cookie is only optionally used by the WebSDK based on config settings. https://experienceleague.adobe.com/docs/experience-platform/edge/extension/web-sdk-extension-configuration.html?lang=en#identity Only when "migrate from Visitor API" is checked will the AMCV_ cookie be read/set by the WebSDK.

Seems the diagram and docs should refer to the kndctr cookie and paranthetically mention the AMCV_ cookie rather than omitting the kndctr cookie all together.

**Comment by dwright-adobe** [comment]
@ryrob30 ,
You are correct in that the ECID is only stored in the AMCV_ cookie when `idMigrationEnabled=true` in the Web SDK configuration. I have updated the diagram and bullets to make that clear.

The "kndctr" cookies never actually store the ECID though. There is a kndctr cookie which stores a different "seed" for the ECID, which gets used if the first-party device id is not set. You won't see the ECID in a kndctr cookie. If you have `idMigrationEnabled=false` look for the ECID in the response of the Web SDK request.
