### ISSUE TITLE
The Create Loyalty Schema via UI section is missing a section to add a new field group called Luma Loyalty Field Group 

### ISSUE THREAD

**Issue by kartha01** [AdobeDocs/platform-learn.en#5]
Location: https://experienceleague.adobe.com/docs/platform-learn/getting-started-for-data-architects-and-data-engineers/model-data-in-schemas.html?lang=en#

There is a slight mismatch in the steps for the Create Loyalty Schema creation via UI and REST. When using the REST API, this Field group  is correctly getting created, whereas the UI way does not mention it.

![image](https://user-images.githubusercontent.com/1424502/150591816-bfd3cdc3-abbc-4fe8-8758-fb9572d2f9ab.png)

**Comment by dwright-adobe** [comment]
Thanks @kartha01 , I think you are expecting the schemas in the [Data Architect tutorial](https://experienceleague.adobe.com/docs/platform-learn/getting-started-for-data-architects-and-data-engineers/overview.html) to match exactly what is in the [Importer tool](https://experienceleague.adobe.com/docs/platform-learn/tutorials/import-sample-data.html). At the moment the DA tutorial uses the new Loyalty Details standard field group, while the Importer tool will create a custom field group for loyalty details. We hope to align the two resources in the future, but for the time being they do not match exactly in the schemas or the sample data.
