### ISSUE TITLE
Please, allow to hide  'on this page' frame on right of all documentation pages

### ISSUE THREAD

**Issue by dburwitz** [AdobeDocs/platform-learn.en#5]
The  'on this page' frame on right of all documentation pages wastes precious screen space. Please, allow user to hide it.
The left 'navigation' frame can be hidden, freeing up space. But after that, the page body gets only 50% of window width. The remaining 50% are taken by the right  'on this page' frame on  documentation pages.
Issue in ./help/tutorial-comprehensive-technical-v21/modules/module11/ex1.md

**Comment by dwright-adobe** [comment]
Thanks @dburwitz , I've submitted this feedback to the Experience League product team via JIRA and cc'd you on that ticket. Closing this git issue. Thanks for taking the time to send us this feedback!
