### ISSUE TITLE
WebSDK Send parameters code does not work. Need to update document.

### ISSUE THREAD

**Issue by techlearning8** [AdobeDocs/platform-learn.en#55]
Issue in ./help/tutorial-migrate-target-websdk/send-parameters.md

Below code does not work to pass parameter/send it to Target 

alloy("sendEvent", {
  "data": {
    "__adobe": {
      "target": {
        "profile.gender": "male",
        "user.categoryId": "clothing"
      }
    }
  }
});

**Comment by dwright-adobe** [comment]
This was a product issue, not a content issue.
