### ISSUE TITLE
Missing a word

### ISSUE THREAD

**Issue by ericthibeault-adobe** [AdobeDocs/platform-learn.en#57]
Issue in ./help/tutorial-web-sdk/configure-schemas.md
https://experienceleague.adobe.com/docs/platform-learn/implement-web-sdk/initial-configuration/configure-schemas.html?lang=en#:~:text=Now%20you%20are%20able%20to%20reference%20this%20schema%20when%20you%20add%20the%20Web%20SDK%20extension%20your%20tag%20property

Missing "to"

**Comment by dwright-adobe** [comment]
This has been updated and should publish in the next few hours. Thanks for the feedback!
