### ISSUE TITLE
The sample page link is not working.

### ISSUE THREAD

**Issue by chetkuma** [AdobeDocs/platform-learn.en#61]
Issue in ./help/tutorial-website-implementation/overview.md
https://experienceleague.adobe.com/docs/platform-learn/implement-in-websites/overview.html?lang=en

Download the [sample html page](https://www.enablementadobe.com/multi/web/basic-sample.html) (right-click on this link and click “Save Link As”)

there is no sample page in the link above.

**Comment by dwright-adobe** [comment]
The sample code has been added to this page. Sorry about the broken link!
