### ISSUE TITLE
The URL for Adding datasets for content experiment reporting is detailed in this section is not found

### ISSUE THREAD

**Issue by immany** [AdobeDocs/platform-learn.en#78]
Issue in ./help/tutorial-web-sdk/setup-web-channel.md

The URL for Adding datasets for content experiment reporting is detailed in this section is not found

>https://experienceleague.adobe.com/en/docs/journey-optimizer/using/campaigns/content-experiment/reporting-configuration?lang=en#add-datasets

**Comment by dwright-adobe** [comment]
Thanks for reporting this. The correct URL is: https://experienceleague.adobe.com/en/docs/journey-optimizer/using/content-management/content-experiment/reporting-configuration#add-datasets

I have updated the tutorial and the updated link should be published shortly.
