### ISSUE TITLE
Need to update the following.

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/platform-learn.en#79]
Issue in ./help/platform/data-ingestion/understanding-streaming-ingestion.md

The video references "Using Experience Platforms streaming ingestion, you can be sure that any data you send will be available in the real-time customer profile in under a second."

This is only accurate for the edge profile. The hub profile it can take up to 15 minutes for ingestion into the profile store.

**Comment by dwright-adobe** [comment]
done
