### ISSUE TITLE
Broken Link - Products

### ISSUE THREAD

**Issue by alberto-decaro** [AdobeDocs/platform-learn.en#8]
Issue in ./help/tutorial-comprehensive-technical-v21/modules/module1/ex5.md

How to reproduce the issue:
1. Browse page https://experienceleague.adobe.com/docs/platform-learn/comprehensive-technical-tutorial-v21/module1/ex5.html
2. Scroll to section 1.5.1. 
2. Go to the 3rd paragraph.
3. Click the [Products](https://experienceleague.adobe.com/docs/experience-platform/edge/implement/commerce.html?lang=en) link
![image](https://user-images.githubusercontent.com/2655809/113630961-0421f980-9669-11eb-8de7-fae8d6fd392a.png)

4. A page not found error is displayed
![image](https://user-images.githubusercontent.com/2655809/113630885-e8b6ee80-9668-11eb-9102-d12c304dd716.png)

**Comment by dwright-adobe** [comment]
@woutervangeluwe

**Comment by woutervangeluwe** [comment]
@dwright-adobe this is also fixed
